config/routes.rb
IndeedScraper::Application.routes.draw do
  resources :job_posts

end

app/models/job_post.rb
class JobPost
  include NoBrainer::Document

  field :job_id
  field :title
  field :link
  field :company
  field :location
  field :summary
  field :days_ago
  field :source
  field :country_code

  def self.find_or_create_by_job_id job_id, hash
    unless (r=JobPost.where(job_id:job_id)).count > 0
      jp=JobPost.create(hash)
    end

    jp || r.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController
  before_action :set_job_post, only: [:show, :edit, :update, :destroy]

  # GET /job_posts
  # GET /job_posts.json
  def index
    @job_posts = JobPost.all
  end

  # GET /job_posts/1
  # GET /job_posts/1.json
  def show
  end

  # GET /job_posts/new
  def new
    @job_post = JobPost.new
  end

  # GET /job_posts/1/edit
  def edit
  end

  # POST /job_posts
  # POST /job_posts.json
  def create
    @job_post = JobPost.new(job_post_params)

    respond_to do |format|
      if @job_post.save
        format.html { redirect_to @job_post, notice: 'Job post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job_post }
      else
        format.html { render action: 'new' }
        format.json { render json: @job_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_posts/1
  # PATCH/PUT /job_posts/1.json
  def update
    respond_to do |format|
      if @job_post.update(job_post_params)
        format.html { redirect_to @job_post, notice: 'Job post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_posts/1
  # DELETE /job_posts/1.json
  def destroy
    @job_post.destroy
    respond_to do |format|
      format.html { redirect_to job_posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_post
      @job_post = JobPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_post_params
      params[:job_post]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/views/job_posts/_form.html.erb
<%= form_for(@job_post) do |f| %>
  <% if @job_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_post.errors.count, "error") %> prohibited this job_post from being saved:</h2>

      <ul>
      <% @job_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_posts/edit.html.erb
<h1>Editing job_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_post %> |
<%= link_to 'Back', job_posts_path %>

app/views/job_posts/index.html.erb
<h1>Listing job_posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Desc</th>
      <th>Country</th>
    </tr>
  </thead>

  <tbody>
    <% @job_posts.each do |job_post| %>
      <tr>
        <td><%= job_post.title %></td>
        <td><%= job_post.summary %></td>
        <td><%= job_post.country_code %></td>
        <td><%= link_to 'Show', job_post %></td>
        <td><%= link_to 'Edit', edit_job_post_path(job_post) %></td>
        <td><%= link_to 'Destroy', job_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job post', new_job_post_path %>

app/views/job_posts/new.html.erb
<h1>New job_post</h1>

<%= render 'form' %>

<%= link_to 'Back', job_posts_path %>

app/views/job_posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_job_post_path(@job_post) %> |
<%= link_to 'Back', job_posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IndeedScraper</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>